### PR TITLE
Add "using" method

### PR DESCRIPTION
**Pull request by dhaub**
Added new "using" and "xusing" methods.  These methods work just like the "all" methods, except they map to "describe" rather than "it".  These methods allow more complex data driven tests.

### CODE REVIEW

**Comment by gburghardt** [comment]
Can you tell me a little more about why the `using` and `xusing` functions are useful? From the code in the merge request, it looks like a way to DRY up repetitive data passed to each test in a `describe` block. Is that a fair thing to assume or is there something more?

**Comment by dhaub** [comment]
You are correct.  I have data driven tests that are better understood as a
_describe_ block than an _it_ block.

**Comment by gburghardt** [comment]
I'm interested in this pull request. Can you update the README with a more realistic example of when this would be useful or describe that here?

**Comment by dhaub** [comment]
Greg,
Here's another example, but I don't know that it is any clearer.  My
testing style is to have a separate it block for each expectation, which is
what makes the using so helpful.

David

using('Account Transfer', [
    [10,  5,  3,  7,  8,  3], // transfer works
    [10,  0, 10,  0, 10, 10], // transfer works
    [10, 10, 11, 10, 10,  0], // transfer doesn't work
  ], function (thisBalance, thatBalance, transferAmount,
expectedThisBalance, expectedThatBalance, expectedTransferAmount) {
    var thisAccount, thatAccount, actualTransferAmount;

```
beforeEach(function () {
  thisAccount = new Account(thisBalance);
  thatAccount = new Account(thatBalance);
  actualTransferAmount = thisAccount.transferTo(thatAccount,
```

transferAmount);
    });

```
it('should have transferred the expected amount of funds', function () {
  expect(actualTransferAmount).toBe(expectedTransferAmount);
});

it('should have correct funds in THIS account', function () {
  expect(thisAccount.balance).toBe(expectedThisBalance);
});

it('should have correct funds in THAT account', function () {
  expect(thatAccount.balance).toBe(expectedThatBalance);
});
```

  });

**Comment by gburghardt** [comment]
Version 1.1.0 includes this functionality. Thanks!

**Comment by dhaub** [comment]
Thank you Greg for this wonderful library.  It has dramatically changed the
way I'm writing my tests.

**Pull request merged**
